learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
#tempalte taging
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.conf.urls import  url, include
from basic_app import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render



def index(requests):
    context_dict = {'text':'hello world', 'number':100}
    return render(requests, 'basic_app/index.html', context_dict)
def relative(requests):
    return render(requests, 'basic_app/rel_url_temp.html')
def other(requests):
    return render(requests, 'basic_app/other.html')

learning_templates/templates/basic_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="#">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">OTHER</a></li>
        </ul>
      </div>
      <div class="container">
        {% block body_block %}
          Anything outside of this will be inherited if extended
        {% endblock %}
      </div>
    </nav>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/basic.html" %}
  {% block body_block %}
    <h1>Welsome to index</h1>
    <h2>This is temp inheritance</h2>
    <h1>{{ text|cut:"hello" }}</h1>
    {{ number|add:"99" }}
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is temp inheritance</h2>
  {% endblock %}

learning_templates/templates/basic_app/rel_url_temp.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to rel url temp</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a>
  </body>
</html>